### ISSUE TITLE
Apple, Google, Discord logos look different than the official logos

### ISSUE THREAD

**Issue by la55u** [phosphor-icons/core#6]
While trying to add some logos in a project, I noticed that the Apple, Google and Discord logos look wildly different than the original ones. Is this intentional? The curves, weight, shapes do not match the ones provided by these brands. All of these icons have official SVG brand assets provided for free, wouldn't it be a better idea to use those and add the Phosphor specific features on top of them instead of redrawing all?
(Please ignore the color differences, I just couldn't find a black google logo)

![Untitled](https://user-images.githubusercontent.com/30611343/225622209-bf575a4f-1992-4656-99c0-d140972e2d04.png)

**Comment by rektdeckard** [comment]
This is intentional. We are not a logos library, and we do our own take on brand icons. There are plenty of options out there ([Devicon](https://devicon.dev/) and [Simple Icons](https://simpleicons.org/) for example) if what you're looking for is official logos. We don't recommend using our brand icons where official first-party assets are needed, whether for clarity or to comply with brand usage guidelines.
